//! Kubernetes protobuf types (v1.32.0), generated by `build.rs` from the
//! vendored `.proto` files under `crates/r8s-types/proto/k8s.io/...`.
//!
//! These are raw prost messages — no serde derives. Converters to
//! `serde_json::Value` (the shape r8s stores and serves over HTTP) live in
//! [`crate::k8s_pb_serde`].
//!
//! The included file `k8s_pb.rs` is emitted by `prost-build` via
//! `Config::include_file`, which wraps every proto package in a nested module
//! tree (`mod k8s { mod io { mod apimachinery { ... } } }`) so cross-package
//! `super::super::...` references between generated files resolve correctly.

include!(concat!(env!("OUT_DIR"), "/k8s_pb.rs"));

/// Convenience re-exports of the module paths we actually use.
pub use k8s::io::api::admissionregistration::v1 as admissionregistration_v1;
pub use k8s::io::api::coordination::v1 as coordination_v1;
pub use k8s::io::api::core::v1 as core_v1;
pub use k8s::io::apiextensions_apiserver::pkg::apis::apiextensions::v1 as apiextensions_v1;
pub use k8s::io::apimachinery::pkg::api::resource;
pub use k8s::io::apimachinery::pkg::apis::meta::v1 as meta_v1;
pub use k8s::io::apimachinery::pkg::runtime;
pub use k8s::io::apimachinery::pkg::util::intstr;
